evenhub.rest.client.daoApiEndpoint=${DAO_API_ENDPOINT:http://event-hub-backend-service:${BACKEND_PORT:8080}}
evenhub.rest.client.schemaApiEndpoint=${SCHEMA_API_ENDPOINT:http://event-hub-schema:${SCHEMA_PORT:8080}}
evenhub.rest.client.publisherApiEndpoint=${PUBLISHER_API_ENDPOINT:http://event-hub-publisher:${PUBLISHER_PORT:8080}}