apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-hub-schema
  labels:
    app: event-hub-schema
    tier: validator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-hub-schema
      tier: validator
  template:
    metadata:
      labels:
        app: event-hub-schema
        tier: validator
    spec:
      serviceAccountName: event-hub-schema-app
      containers:
        - name: event-hub-schema
          image: gcr.io/event-hub-317019/event-hub-schema:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
