project_id   = "event-hub-317019"
region       = "us-central1"
cluster_name = "prod-autopilot-cluster"
vpc_name     = "main-gke-vpc"
subnet_name  = "gke-nodes-subnet"
cicd_service_account_email = "github-cicd-sa@event-hub-317019.iam.gserviceaccount.com"