name: Terraform Deploy
on:   
  # Trigger only if files in this folder change
  pull_request:
    branches:
      - main
    paths:
      - 'services/event-hub-infra-terraform/gcp/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for OIDC handshake

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # Use the output from the Terraform code above
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'terraform-gke-admin@your-project.iam.gserviceaccount.com'

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve